#################### default parameters ################################
logo = "images/logo.svg"
logo_width = "200px"
# Meta data
description = "AashrayBuild Construction and Service"
author = "Amol"
# contact form action
contact_form_action = "#" # contact form works with https://formspree.io

# Preloader
[preloader]
enable = true
preloader = "images/logo.png" # use jpg, png, svg or gif format.

# Navigation buttons
[navigation_button]
enable = true
label = "Get Started"
link = "contact"

  
############################# social site ########################
[[social]]
title = "facebook"
icon = "fab fa-facebook" # themify icon : https://themify.me/themify-icons
link = "https://www.facebook.com/AashrayBuild"

[[social]]
title = "twitter"
icon = "fab fa-twitter" # themify icon : https://themify.me/themify-icons
link = "https://twitter.com/AashrayBuild"

[[social]]
title = "Instagram"
icon = "fab fa-instagram" # themify icon : https://themify.me/themify-icons
link = "https://www.instagram.com/aashraybuild/"