[build]
  publish = "public/"
  command = "hugo --gc --minify"

[build.environment]
  HUGO_VERSION = "0.80.0"

[context.deploy-preview]
  command = "hugo --gc --minify --buildFuture --baseURL ${DEPLOY_PRIME_URL}"

[context.branch-deploy]
  command = "hugo --gc --minify --buildFuture --baseURL ${DEPLOY_PRIME_URL}"
